#!/bin/sh

set -e

yellow=$(tput setaf 3)
normal=$(tput sgr0)

case "$1" in
    configure)
        if [ "x"$2 != "x" ]; then
            # we are doing an upgrade
            exit 0
        fi
        cat /etc/shadow | awk -F ':' '{ print $1 }' | grep -E '^barnyard2$' > /dev/null || useradd -G adm -d /var/log/barnyard2/ -c 'Barnyard2 spool reader' -r barnyard2
        chown -R barnyard2: /var/log/barnyard2/
        update-rc.d barnyard2 defaults
    ;;
    
    abort-upgrade|abort-remove|abort-deconfigure)
    ;;
    
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
